-- 학적조회(WP-150 설계 / WP-151 API) — 스키마
--
-- 근거: docs/2026-08-23_academic-record-table-design.md (테이블 설계 확정본)
-- 운영은 ddl-auto: validate라 이 파일을 직접 실행해야 한다.
--
-- 멱등: CREATE TABLE은 IF NOT EXISTS라 여러 번 실행해도 안전하다.

-- ════════════════════════════════════════════════════════════════════
-- 1. CREATE TABLE — student_academic_detail (1:1, app_user 종속)
-- ════════════════════════════════════════════════════════════════════
-- 학교 본원 시스템에서 학적정보가 이미 채워진 학생이 넘어온 이후의 서비스라는 전제로,
-- 이 프로젝트에 회원가입/입학처리 절차가 없어도 그 시점에 항상 확정돼 있는 값
-- (major_code_id/birth_date/gender/grade)은 NOT NULL로 건다. 그 외(주소/지도교수/증명사진/
-- 학위정보/이수학기)는 이 프로젝트 안에서 별도 절차로 채워지거나 학기마다 갱신되는 값이라
-- nullable로 둔다.
CREATE TABLE IF NOT EXISTS student_academic_detail (
    user_id              INTEGER PRIMARY KEY REFERENCES app_user(user_id),
    major_code_id        INTEGER NOT NULL REFERENCES common_code(code_id),
    advisor_user_id      INTEGER REFERENCES app_user(user_id),
    photo_file_group_id  INTEGER REFERENCES file_group(file_group_id),

    birth_date           DATE NOT NULL,
    gender               CHAR(1) NOT NULL CHECK (gender IN ('M', 'F')),

    zipcode              VARCHAR(10),
    address_basic        VARCHAR(255),
    address_detail       VARCHAR(255),
    guardian_phone       VARCHAR(30),

    grade                SMALLINT NOT NULL CHECK (grade BETWEEN 1 AND 4),
    completed_semesters  SMALLINT,
    degree_name          VARCHAR(50),
    degree_no            VARCHAR(50),

    created_at           TIMESTAMP NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sad_major ON student_academic_detail(major_code_id);
CREATE INDEX IF NOT EXISTS idx_sad_grade ON student_academic_detail(grade);

-- ════════════════════════════════════════════════════════════════════
-- 2. CREATE TABLE — student_academic_change (1:N, append-only)
-- ════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS student_academic_change (
    student_academic_change_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id                      INTEGER NOT NULL REFERENCES app_user(user_id),
    change_date                     DATE    NOT NULL,
    change_type_code_id             INTEGER NOT NULL REFERENCES common_code(code_id),
    change_reason_code_id           INTEGER REFERENCES common_code(code_id),
    military_status                 VARCHAR(20),
    scheduled_return_year           SMALLINT,
    scheduled_return_semester_code  VARCHAR(20),
    note                             VARCHAR(500),
    created_by                      INTEGER NOT NULL,
    created_at                      TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sac_student_date
    ON student_academic_change(student_id, change_date DESC, student_academic_change_id DESC);
