-- ============================================================================
-- 학생 통합 역량 관리 시스템 (SCMS) - 통합 DDL 스크립트 (PostgreSQL 18 기준)
-- ============================================================================

-- 0. 확장 기능 활성화 (pgvector 등)
-- CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- 1. 공통 및 사용자 도메인 (Common & User)
-- ============================================================================

CREATE TABLE app_user (
                          user_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          login_id            VARCHAR(100) NOT NULL UNIQUE,
                          password_hash       VARCHAR(255) NOT NULL,
                          user_name           VARCHAR(100) NOT NULL,
                          user_type           VARCHAR(30) NOT NULL,
                          department_code     VARCHAR(50),
                          academic_status     VARCHAR(30),
                          email               VARCHAR(255),
                          phone_number        VARCHAR(30),
                          is_active           BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE consent_policy (
                                consent_policy_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                consent_type        VARCHAR(40) NOT NULL,
                                module_code         VARCHAR(30) NOT NULL,
                                version             VARCHAR(30) NOT NULL,
                                title               VARCHAR(200) NOT NULL,
                                content             TEXT NOT NULL,
                                is_required         BOOLEAN NOT NULL,
                                effective_from      TIMESTAMPTZ NOT NULL,
                                effective_to        TIMESTAMPTZ,
                                is_active           BOOLEAN NOT NULL DEFAULT TRUE,
                                created_by          INTEGER NOT NULL,
                                created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT uq_consent_policy_type_module_version UNIQUE (consent_type, module_code, version)
);

CREATE TABLE user_consent (
                              user_consent_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id             INTEGER NOT NULL REFERENCES app_user(user_id),
                              consent_policy_id   INTEGER NOT NULL REFERENCES consent_policy(consent_policy_id),
                              consented_at        TIMESTAMPTZ NOT NULL,
                              withdrawn_at        TIMESTAMPTZ,
                              created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uq_user_consent_active
    ON user_consent (user_id, consent_policy_id)
    WHERE withdrawn_at IS NULL;

CREATE TABLE common_code (
                             code_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             parent_code_id      INTEGER REFERENCES common_code(code_id),
                             code_group          VARCHAR(50) NOT NULL,
                             code                VARCHAR(50) NOT NULL,
                             code_name           VARCHAR(100) NOT NULL,
                             description         TEXT,
                             sort_order          INTEGER NOT NULL DEFAULT 0,
                             is_active           BOOLEAN NOT NULL DEFAULT TRUE,
                             created_by          INTEGER NOT NULL,
                             created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT uq_common_code_group_code UNIQUE (code_group, code),
                             CONSTRAINT uq_common_code_id_group UNIQUE (code_id, code_group)
);

CREATE TABLE file_group (
                            file_group_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stored_file (
                             stored_file_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             file_group_id       INTEGER NOT NULL REFERENCES file_group(file_group_id),
                             original_file_name  VARCHAR(255) NOT NULL,
                             storage_key         VARCHAR(1000) NOT NULL UNIQUE,
                             content_type        VARCHAR(100),
                             file_size           BIGINT NOT NULL,
                             uploaded_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             created_by          INTEGER NOT NULL
);

CREATE TABLE audit_log (
                           audit_log_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           actor_user_id       INTEGER,
                           resource_type       VARCHAR(80) NOT NULL,
                           resource_id         INTEGER,
                           action_code         VARCHAR(30) NOT NULL,
                           action_result       VARCHAR(20) NOT NULL,
                           access_reason       VARCHAR(500),
                           ip_address          VARCHAR(45),
                           user_agent          VARCHAR(500),
                           created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notification (
                              notification_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              recipient_user_id   INTEGER NOT NULL REFERENCES app_user(user_id),
                              notification_type   VARCHAR(40) NOT NULL,
                              module_code         VARCHAR(30) NOT NULL,
                              channel             VARCHAR(20) NOT NULL,
                              title               VARCHAR(200) NOT NULL,
                              content             TEXT NOT NULL,
                              delivery_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                              retry_count         INTEGER NOT NULL DEFAULT 0,
                              failure_reason      TEXT,
                              sent_at             TIMESTAMPTZ,
                              read_at             TIMESTAMPTZ,
                              created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE board_post (
                            board_post_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            parent_post_id      INTEGER REFERENCES board_post(board_post_id),
                            file_group_id       INTEGER REFERENCES file_group(file_group_id),
                            author_user_id      INTEGER NOT NULL REFERENCES app_user(user_id),
                            board_type          VARCHAR(20) NOT NULL,
                            module_code         VARCHAR(30) NOT NULL,
                            category_code       VARCHAR(40),
                            title               VARCHAR(300) NOT NULL,
                            content             TEXT NOT NULL,
                            is_private          BOOLEAN NOT NULL DEFAULT FALSE,
                            is_pinned           BOOLEAN NOT NULL DEFAULT FALSE,
                            post_status         VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
                            deleted_at          TIMESTAMPTZ,
                            created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- ============================================================================
-- 2. 학적 도메인 (Academic)
-- ============================================================================

CREATE TABLE student_academic_detail (
                                         user_id              INTEGER PRIMARY KEY REFERENCES app_user(user_id),
                                         major_code_id        INTEGER NOT NULL,
                                         advisor_user_id      INTEGER REFERENCES app_user(user_id),
                                         photo_file_group_id  INTEGER REFERENCES file_group(file_group_id),
                                         birth_date           DATE NOT NULL,
                                         gender               CHAR(1) NOT NULL CHECK (gender IN ('M', 'F')),
                                         zipcode              VARCHAR(10),
                                         address_basic        VARCHAR(255),
                                         address_detail       VARCHAR(255),
                                         guardian_phone       VARCHAR(30),
                                         grade                SMALLINT NOT NULL CHECK (grade BETWEEN 1 AND 4),
                                         completed_semesters  SMALLINT,
                                         degree_name          VARCHAR(50),
                                         degree_no            VARCHAR(50),
                                         created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         major_code_group     VARCHAR(50) GENERATED ALWAYS AS ('MAJOR') STORED,
                                         CONSTRAINT fk_sad_major_code_group FOREIGN KEY (major_code_id, major_code_group) REFERENCES common_code (code_id, code_group)
);

CREATE INDEX idx_sad_major ON student_academic_detail(major_code_id);
CREATE INDEX idx_sad_grade ON student_academic_detail(grade);

CREATE TABLE student_academic_change (
                                         student_academic_change_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         student_id                      INTEGER NOT NULL REFERENCES app_user(user_id),
                                         change_date                     DATE NOT NULL,
                                         change_type_code_id             INTEGER NOT NULL,
                                         change_reason_code_id           INTEGER REFERENCES common_code(code_id),
                                         military_status                 VARCHAR(20),
                                         scheduled_return_year           SMALLINT,
                                         scheduled_return_semester_code  VARCHAR(20),
                                         note                            VARCHAR(500),
                                         created_by                      INTEGER NOT NULL,
                                         created_at                      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         change_type_code_group          VARCHAR(50) GENERATED ALWAYS AS ('ACADEMIC_CHANGE_TYPE') STORED,
                                         change_reason_code_group        VARCHAR(50) GENERATED ALWAYS AS ('ACADEMIC_CHANGE_REASON') STORED,
                                         CONSTRAINT fk_sac_change_type_code_group FOREIGN KEY (change_type_code_id, change_type_code_group) REFERENCES common_code (code_id, code_group),
                                         CONSTRAINT fk_sac_change_reason_code_group FOREIGN KEY (change_reason_code_id, change_reason_code_group) REFERENCES common_code (code_id, code_group)
);

CREATE INDEX idx_sac_student_date ON student_academic_change(student_id, change_date DESC, student_academic_change_id DESC);


-- ============================================================================
-- 3. 핵심역량 및 진단 도메인 (Competency & Assessment)
-- ============================================================================

CREATE TABLE competency (
                            competency_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            parent_competency_id    INTEGER REFERENCES competency(competency_id),
                            competency_code         VARCHAR(20) NOT NULL UNIQUE,
                            competency_name         VARCHAR(100) NOT NULL,
                            english_name            VARCHAR(150),
                            description             TEXT,
                            display_order           INTEGER NOT NULL,
                            is_active               BOOLEAN NOT NULL DEFAULT TRUE,
                            created_by              INTEGER NOT NULL,
                            created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assessment_round (
                                  assessment_round_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  assessment_name         VARCHAR(200) NOT NULL,
                                  academic_year           INTEGER NOT NULL,
                                  semester_code           VARCHAR(20) NOT NULL,
                                  assessment_type         VARCHAR(20) NOT NULL,
                                  starts_at               TIMESTAMPTZ NOT NULL,
                                  ends_at                 TIMESTAMPTZ NOT NULL,
                                  target_condition        JSONB,
                                  round_status            VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
                                  created_by              INTEGER NOT NULL,
                                  created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT uq_assessment_round_period_type UNIQUE (academic_year, semester_code, assessment_type)
);

CREATE TABLE assessment_question (
                                     question_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     competency_id           INTEGER NOT NULL REFERENCES competency(competency_id),
                                     previous_question_id    INTEGER REFERENCES assessment_question(question_id),
                                     version_no              INTEGER NOT NULL DEFAULT 1,
                                     question_text           TEXT NOT NULL,
                                     is_reverse              BOOLEAN NOT NULL DEFAULT FALSE,
                                     response_options        JSONB NOT NULL,
                                     is_active               BOOLEAN NOT NULL DEFAULT TRUE,
                                     created_by              INTEGER NOT NULL,
                                     created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     CONSTRAINT uq_assessment_question_previous_version UNIQUE (previous_question_id, version_no)
);

CREATE TABLE assessment_round_question (
                                           assessment_round_id     INTEGER NOT NULL REFERENCES assessment_round(assessment_round_id),
                                           question_id             INTEGER NOT NULL REFERENCES assessment_question(question_id),
                                           display_order           INTEGER NOT NULL,
                                           created_by              INTEGER NOT NULL,
                                           PRIMARY KEY (assessment_round_id, question_id),
                                           CONSTRAINT uq_assessment_round_question_order UNIQUE (assessment_round_id, display_order)
);

CREATE TABLE assessment_attempt (
                                    attempt_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    assessment_round_id     INTEGER NOT NULL REFERENCES assessment_round(assessment_round_id),
                                    student_id              INTEGER NOT NULL REFERENCES app_user(user_id),
                                    user_consent_id         INTEGER REFERENCES user_consent(user_consent_id),
                                    attempt_status          VARCHAR(20) NOT NULL DEFAULT 'NOT_STARTED',
                                    started_at              TIMESTAMPTZ,
                                    saved_at                TIMESTAMPTZ,
                                    submitted_at            TIMESTAMPTZ,
                                    created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    CONSTRAINT uq_assessment_attempt_round_student UNIQUE (assessment_round_id, student_id)
);

CREATE TABLE assessment_response (
                                     response_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     attempt_id              INTEGER NOT NULL REFERENCES assessment_attempt(attempt_id),
                                     question_id             INTEGER NOT NULL REFERENCES assessment_question(question_id),
                                     selected_value          NUMERIC(10, 2) NOT NULL,
                                     saved_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     created_by              INTEGER NOT NULL,
                                     CONSTRAINT uq_assessment_response_attempt_question UNIQUE (attempt_id, question_id)
);

CREATE TABLE assessment_score (
                                  assessment_score_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  attempt_id              INTEGER NOT NULL REFERENCES assessment_attempt(attempt_id),
                                  competency_id           INTEGER NOT NULL REFERENCES competency(competency_id),
                                  raw_score               NUMERIC(10, 2) NOT NULL,
                                  converted_score         NUMERIC(10, 2) NOT NULL,
                                  percentile              NUMERIC(6, 3),
                                  calculated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT uq_assessment_score_attempt_competency UNIQUE (attempt_id, competency_id)
);


-- ============================================================================
-- 4. 상담 도메인 (Counseling)
-- ============================================================================

CREATE TABLE counseling_type (
                                 counseling_type_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 type_code               VARCHAR(40) NOT NULL UNIQUE,
                                 type_name               VARCHAR(100) NOT NULL,
                                 application_route       VARCHAR(30) NOT NULL,
                                 counseling_method       VARCHAR(30) NOT NULL,
                                 preceding_procedure     VARCHAR(300),
                                 is_active               BOOLEAN NOT NULL DEFAULT TRUE,
                                 created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 created_by              INTEGER NOT NULL REFERENCES app_user(user_id)
);

CREATE TABLE counseling_schedule (
                                     counseling_schedule_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     counseling_type_id      INTEGER NOT NULL REFERENCES counseling_type(counseling_type_id),
                                     counselor_id            INTEGER NOT NULL REFERENCES app_user(user_id),
                                     starts_at               TIMESTAMPTZ NOT NULL,
                                     ends_at                 TIMESTAMPTZ NOT NULL,
                                     capacity                INTEGER NOT NULL DEFAULT 1,
                                     booking_deadline        TIMESTAMPTZ,
                                     location                VARCHAR(300),
                                     schedule_status         VARCHAR(20) NOT NULL DEFAULT 'OPEN',
                                     created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE counseling_reservation (
                                        counseling_reservation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        counseling_type_id        INTEGER NOT NULL REFERENCES counseling_type(counseling_type_id),
                                        counseling_schedule_id    INTEGER REFERENCES counseling_schedule(counseling_schedule_id),
                                        student_id                INTEGER NOT NULL REFERENCES app_user(user_id),
                                        user_consent_id           INTEGER REFERENCES user_consent(user_consent_id),
                                        request_content           TEXT NOT NULL,
                                        intake_data               JSONB,
                                        reservation_status        VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
                                        processed_by              INTEGER REFERENCES app_user(user_id),
                                        processed_at              TIMESTAMPTZ,
                                        decision_reason           TEXT,
                                        canceled_at               TIMESTAMPTZ,
                                        cancellation_reason       TEXT,
                                        change_reason             TEXT,
                                        created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE counseling_assignment (
                                       counseling_assignment_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       counseling_reservation_id INTEGER NOT NULL REFERENCES counseling_reservation(counseling_reservation_id),
                                       counselor_id              INTEGER NOT NULL REFERENCES app_user(user_id),
                                       assigned_by               INTEGER NOT NULL REFERENCES app_user(user_id),
                                       assignment_reason         VARCHAR(500),
                                       assigned_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       ended_at                  TIMESTAMPTZ
);

CREATE TABLE counseling_session (
                                    counseling_session_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    counseling_assignment_id  INTEGER NOT NULL REFERENCES counseling_assignment(counseling_assignment_id),
                                    session_no                INTEGER NOT NULL,
                                    starts_at                 TIMESTAMPTZ NOT NULL,
                                    ends_at                   TIMESTAMPTZ,
                                    attendance_status         VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
                                    session_status            VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
                                    next_session_at           TIMESTAMPTZ,
                                    cancellation_reason       VARCHAR(500),
                                    created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    created_by                INTEGER NOT NULL REFERENCES app_user(user_id),
                                    UNIQUE (counseling_assignment_id, session_no)
);

CREATE TABLE counseling_private_record (
                                           private_record_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           counseling_session_id     INTEGER NOT NULL REFERENCES counseling_session(counseling_session_id),
                                           version_no                INTEGER NOT NULL,
                                           private_content           TEXT NOT NULL,
                                           confirmed_by              INTEGER REFERENCES app_user(user_id),
                                           confirmed_at              TIMESTAMPTZ,
                                           created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           UNIQUE (counseling_session_id, version_no)
);

CREATE TABLE counseling_public_result (
                                          public_result_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          counseling_session_id     INTEGER NOT NULL REFERENCES counseling_session(counseling_session_id),
                                          version_no                INTEGER NOT NULL,
                                          result_summary            TEXT NOT NULL,
                                          action_plan               TEXT,
                                          follow_up_data            JSONB,
                                          correction_reason         VARCHAR(500),
                                          published_at              TIMESTAMPTZ,
                                          created_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                          created_by                INTEGER NOT NULL REFERENCES app_user(user_id),
                                          UNIQUE (counseling_session_id, version_no)
);

CREATE TABLE psychological_test_question (
                                             psychological_test_question_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             test_type                      VARCHAR(40) NOT NULL,
                                             test_version                   VARCHAR(30) NOT NULL,
                                             question_no                    INTEGER NOT NULL,
                                             question_text                  TEXT NOT NULL,
                                             response_options               JSONB NOT NULL,
                                             created_at                     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             UNIQUE (test_type, test_version, question_no)
);

CREATE TABLE psychological_test_result (
                                           psychological_test_result_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           student_id                  INTEGER NOT NULL REFERENCES app_user(user_id),
                                           counseling_reservation_id   INTEGER REFERENCES counseling_reservation(counseling_reservation_id),
                                           test_type                   VARCHAR(40) NOT NULL,
                                           test_version                VARCHAR(30) NOT NULL,
                                           total_score                 NUMERIC(8, 2) NOT NULL,
                                           result_level                VARCHAR(50) NOT NULL,
                                           result_summary              TEXT NOT NULL,
                                           tested_at                   TIMESTAMPTZ NOT NULL,
                                           created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE counseling_proposal (
                                     counseling_proposal_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     student_id                   INTEGER NOT NULL REFERENCES app_user(user_id),
                                     proposed_by                  INTEGER NOT NULL REFERENCES app_user(user_id),
                                     psychological_test_result_id INTEGER NOT NULL REFERENCES psychological_test_result(psychological_test_result_id),
                                     created_reservation_id       INTEGER REFERENCES counseling_reservation(counseling_reservation_id),
                                     proposal_content             TEXT NOT NULL,
                                     response_status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                     response_deadline            TIMESTAMPTZ,
                                     responded_at                 TIMESTAMPTZ,
                                     created_at                   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     CONSTRAINT uq_counseling_proposal_test_result UNIQUE (psychological_test_result_id)
);


-- ============================================================================
-- 5. 취창업 도메인 (Career)
-- ============================================================================

CREATE TABLE company_account (
                                 company_account_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 company_name               VARCHAR(200) NOT NULL,
                                 business_registration_no   VARCHAR(30) NOT NULL UNIQUE,
                                 login_id                   VARCHAR(100) UNIQUE,
                                 password_hash              VARCHAR(255),
                                 representative_name        VARCHAR(100),
                                 contact_name               VARCHAR(100) NOT NULL,
                                 contact_phone              VARCHAR(30),
                                 contact_email              VARCHAR(255) NOT NULL,
                                 address                    VARCHAR(500),
                                 verification_status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                 verified_by                INTEGER,
                                 verified_at                TIMESTAMPTZ,
                                 account_status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                                 created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE career_document (
                                 career_document_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 file_group_id              INTEGER REFERENCES file_group(file_group_id),
                                 student_id                 INTEGER NOT NULL REFERENCES app_user(user_id),
                                 document_type              VARCHAR(30) NOT NULL,
                                 version_no                 INTEGER NOT NULL,
                                 document_title             VARCHAR(200) NOT NULL,
                                 content_data               JSONB,
                                 is_public                  BOOLEAN NOT NULL DEFAULT FALSE,
                                 ai_assistance_used         BOOLEAN NOT NULL DEFAULT FALSE,
                                 created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 CONSTRAINT uq_career_document_student_type_version UNIQUE (student_id, document_type, version_no)
);

CREATE TABLE employment_record (
                                   employment_record_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   file_group_id              INTEGER REFERENCES file_group(file_group_id),
                                   student_id                 INTEGER NOT NULL REFERENCES app_user(user_id),
                                   company_account_id         INTEGER REFERENCES company_account(company_account_id),
                                   entered_by                 INTEGER,
                                   verified_by                INTEGER,
                                   company_name               VARCHAR(200) NOT NULL,
                                   employment_start_date      DATE NOT NULL,
                                   employment_type            VARCHAR(30),
                                   evidence_type              VARCHAR(30),
                                   employment_status          VARCHAR(20) NOT NULL DEFAULT 'REPORTED',
                                   employment_detail          JSONB,
                                   verified_at                TIMESTAMPTZ,
                                   month_3_status             VARCHAR(30),
                                   month_6_status             VARCHAR(30),
                                   month_11_status            VARCHAR(30),
                                   created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employment_statistic (
                                      employment_statistic_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      academic_year              INTEGER NOT NULL,
                                      department_code_id         INTEGER NOT NULL REFERENCES common_code(code_id),
                                      statistic_type             VARCHAR(30) NOT NULL,
                                      graduate_count             INTEGER,
                                      employed_count             INTEGER,
                                      employment_rate            NUMERIC(7, 4),
                                      maintenance_rate           NUMERIC(7, 4),
                                      statistic_source           VARCHAR(100) NOT NULL,
                                      imported_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      CONSTRAINT uq_employment_statistic_year_department_type UNIQUE (academic_year, department_code_id, statistic_type)
);

CREATE TABLE employment_survey_response (
                                            employment_survey_response_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            survey_type                   VARCHAR(30) NOT NULL,
                                            respondent_user_id            INTEGER REFERENCES app_user(user_id),
                                            company_account_id            INTEGER REFERENCES company_account(company_account_id),
                                            response_data                 JSONB NOT NULL,
                                            sent_at                       TIMESTAMPTZ,
                                            responded_at                  TIMESTAMPTZ,
                                            created_at                    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job_posting (
                             job_posting_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             company_account_id         INTEGER NOT NULL REFERENCES company_account(company_account_id),
                             ncs_code_id                INTEGER REFERENCES common_code(code_id),
                             region_code_id             INTEGER REFERENCES common_code(code_id),
                             reviewed_by                INTEGER,
                             posting_title              VARCHAR(250) NOT NULL,
                             job_description            TEXT NOT NULL,
                             recruitment_count          INTEGER,
                             employment_type            VARCHAR(30),
                             salary_text                VARCHAR(100),
                             qualification_data         JSONB,
                             application_starts_at      TIMESTAMPTZ,
                             application_ends_at        TIMESTAMPTZ NOT NULL,
                             posting_type               VARCHAR(30) NOT NULL DEFAULT 'GENERAL',
                             benefit_type               VARCHAR(30),
                             review_status              VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
                             reviewed_at                TIMESTAMPTZ,
                             rejection_reason           TEXT,
                             posting_status             VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
                             submitted_at               TIMESTAMPTZ,
                             published_at               TIMESTAMPTZ,
                             created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE job_preference (
                                job_preference_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                student_id                 INTEGER NOT NULL UNIQUE REFERENCES app_user(user_id),
                                ncs_code_id                INTEGER REFERENCES common_code(code_id),
                                preferred_region_code_id   INTEGER REFERENCES common_code(code_id),
                                preferred_employment_type  VARCHAR(30),
                                minimum_salary             NUMERIC(14, 2),
                                created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ncs_standard (
                              ncs_standard_id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              ncs_code                   VARCHAR(50) NOT NULL UNIQUE,
                              category_name              VARCHAR(255),
                              job_description            TEXT,
                              embedding_vector           vector
);

CREATE TABLE student_job_relation (
                                      student_job_relation_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      student_id                 INTEGER NOT NULL REFERENCES app_user(user_id),
                                      job_posting_id             INTEGER NOT NULL REFERENCES job_posting(job_posting_id),
                                      user_consent_id            INTEGER REFERENCES user_consent(user_consent_id),
                                      matching_score             NUMERIC(6, 2),
                                      matching_status            VARCHAR(20),
                                      matched_at                 TIMESTAMPTZ,
                                      bookmarked_at              TIMESTAMPTZ,
                                      applied_at                 TIMESTAMPTZ,
                                      canceled_at                TIMESTAMPTZ,
                                      recommendation_source      VARCHAR(30),
                                      application_status         VARCHAR(20),
                                      selection_stage            VARCHAR(50),
                                      selection_result           VARCHAR(30),
                                      created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                      CONSTRAINT uq_student_job_relation_student_posting UNIQUE (student_id, job_posting_id)
);

CREATE TABLE student_profile (
                                 user_id                    INTEGER PRIMARY KEY REFERENCES app_user(user_id),
                                 student_grade              VARCHAR(255),
                                 embedding_vector           vector
);


-- ============================================================================
-- 6. 마일리지 및 비교과 프로그램 도메인 (Mileage & Program)
-- ============================================================================

CREATE TABLE mileage_activity_type (
                                       activity_type_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       competency_id              INTEGER NOT NULL REFERENCES competency(competency_id),
                                       activity_code              VARCHAR(40) NOT NULL UNIQUE,
                                       category_code              VARCHAR(40) NOT NULL,
                                       activity_name              VARCHAR(150) NOT NULL,
                                       earning_route              VARCHAR(30) NOT NULL,
                                       is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
                                       created_by                 INTEGER NOT NULL,
                                       created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                       updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mileage_policy (
                                mileage_policy_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                activity_type_id           INTEGER NOT NULL REFERENCES mileage_activity_type(activity_type_id),
                                academic_year              INTEGER NOT NULL,
                                semester_code              VARCHAR(20) NOT NULL DEFAULT 'ALL',
                                version_no                 INTEGER NOT NULL,
                                points                     NUMERIC(10, 2) NOT NULL,
                                maximum_points             NUMERIC(10, 2),
                                valid_from                 DATE NOT NULL,
                                valid_to                   DATE,
                                duplicate_rule             JSONB,
                                policy_status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
                                created_by                 INTEGER NOT NULL,
                                created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT uq_mileage_policy_activity_period_version UNIQUE (activity_type_id, academic_year, semester_code, version_no)
);

CREATE TABLE extracurricular_program (
                                         program_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         file_group_id              INTEGER REFERENCES file_group(file_group_id),
                                         operating_unit_code_id     INTEGER NOT NULL REFERENCES common_code(code_id),
                                         program_type_code_id       INTEGER NOT NULL REFERENCES common_code(code_id),
                                         competency_id              INTEGER NOT NULL REFERENCES competency(competency_id),
                                         mileage_policy_id          INTEGER REFERENCES mileage_policy(mileage_policy_id),
                                         manager_user_id            INTEGER NOT NULL REFERENCES app_user(user_id),
                                         program_name               VARCHAR(200) NOT NULL,
                                         description                TEXT,
                                         recruitment_starts_at      TIMESTAMPTZ NOT NULL,
                                         recruitment_ends_at        TIMESTAMPTZ NOT NULL,
                                         operation_starts_at        TIMESTAMPTZ NOT NULL,
                                         operation_ends_at          TIMESTAMPTZ NOT NULL,
                                         capacity                   INTEGER NOT NULL,
                                         completion_rate            NUMERIC(5, 2) NOT NULL DEFAULT 80.00,
                                         program_status             VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
                                         updated_by                 INTEGER,
                                         created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         CONSTRAINT uq_extracurricular_program_file_group_id UNIQUE (file_group_id)
);

CREATE TABLE program_application (
                                     application_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     program_id                 INTEGER NOT NULL REFERENCES extracurricular_program(program_id),
                                     student_id                 INTEGER NOT NULL REFERENCES app_user(user_id),
                                     user_consent_id            INTEGER REFERENCES user_consent(user_consent_id),
                                     application_status         VARCHAR(20) NOT NULL DEFAULT 'APPLIED',
                                     waitlist_order             INTEGER,
                                     processed_by               INTEGER,
                                     processed_at               TIMESTAMPTZ,
                                     decision_reason            TEXT,
                                     canceled_at                TIMESTAMPTZ,
                                     cancellation_reason        TEXT,
                                     completion_status          VARCHAR(20),
                                     survey_completed           BOOLEAN NOT NULL DEFAULT FALSE,
                                     certificate_no             VARCHAR(80) UNIQUE,
                                     certificate_issued_at      TIMESTAMPTZ,
                                     judged_by                  INTEGER,
                                     completed_at               TIMESTAMPTZ,
                                     created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     CONSTRAINT uq_program_application_program_student UNIQUE (program_id, student_id)
);

CREATE TABLE program_session (
                                 program_session_id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 program_id                 INTEGER NOT NULL REFERENCES extracurricular_program(program_id),
                                 session_no                 INTEGER NOT NULL,
                                 session_name               VARCHAR(150),
                                 starts_at                  TIMESTAMPTZ NOT NULL,
                                 ends_at                    TIMESTAMPTZ NOT NULL,
                                 location                   VARCHAR(300),
                                 created_by                 INTEGER NOT NULL,
                                 created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                 CONSTRAINT uq_program_session_program_no UNIQUE (program_id, session_no)
);

CREATE TABLE program_attendance (
                                    attendance_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    application_id             INTEGER NOT NULL REFERENCES program_application(application_id),
                                    program_session_id         INTEGER NOT NULL REFERENCES program_session(program_session_id),
                                    attendance_status          VARCHAR(20) NOT NULL,
                                    attended_minutes           INTEGER,
                                    note                       VARCHAR(500),
                                    recorded_by                INTEGER,
                                    recorded_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    CONSTRAINT uq_program_attendance_application_session UNIQUE (application_id, program_session_id)
);

CREATE TABLE external_activity_claim (
                                         external_claim_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         file_group_id              INTEGER REFERENCES file_group(file_group_id),
                                         student_id                 INTEGER NOT NULL REFERENCES app_user(user_id),
                                         activity_type_id           INTEGER NOT NULL REFERENCES mileage_activity_type(activity_type_id),
                                         mileage_policy_id          INTEGER REFERENCES mileage_policy(mileage_policy_id),
                                         activity_name              VARCHAR(200) NOT NULL,
                                         activity_date              DATE NOT NULL,
                                         requested_points           NUMERIC(10, 2),
                                         detail_data                JSONB,
                                         claim_status               VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
                                         reviewed_by                INTEGER,
                                         reviewed_at                TIMESTAMPTZ,
                                         review_reason              TEXT,
                                         created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mileage_benefit_policy (
                                        benefit_policy_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        benefit_type               VARCHAR(20) NOT NULL,
                                        academic_year              INTEGER NOT NULL,
                                        semester_code              VARCHAR(20) NOT NULL DEFAULT 'ALL',
                                        benefit_name               VARCHAR(150) NOT NULL,
                                        minimum_points             NUMERIC(10, 2) NOT NULL,
                                        benefit_amount             NUMERIC(14, 2),
                                        criteria_data              JSONB,
                                        application_starts_at      TIMESTAMPTZ,
                                        application_ends_at        TIMESTAMPTZ,
                                        is_active                  BOOLEAN NOT NULL DEFAULT TRUE,
                                        created_by                 INTEGER NOT NULL,
                                        created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mileage_benefit_application (
                                             benefit_application_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             benefit_policy_id          INTEGER NOT NULL REFERENCES mileage_benefit_policy(benefit_policy_id),
                                             student_id                 INTEGER NOT NULL REFERENCES app_user(user_id),
                                             points_snapshot            NUMERIC(10, 2) NOT NULL,
                                             application_status         VARCHAR(20) NOT NULL DEFAULT 'APPLIED',
                                             processed_by               INTEGER,
                                             processed_at               TIMESTAMPTZ,
                                             decision_reason            TEXT,
                                             applied_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             CONSTRAINT uq_mileage_benefit_application_policy_student UNIQUE (benefit_policy_id, student_id)
);

CREATE TABLE mileage_transaction (
                                     mileage_transaction_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     student_id                    INTEGER NOT NULL REFERENCES app_user(user_id),
                                     mileage_policy_id             INTEGER REFERENCES mileage_policy(mileage_policy_id),
                                     competency_id                 INTEGER NOT NULL REFERENCES competency(competency_id),
                                     source_program_application_id INTEGER UNIQUE REFERENCES program_application(application_id),
                                     source_external_claim_id      INTEGER UNIQUE REFERENCES external_activity_claim(external_claim_id),
                                     source_assessment_attempt_id  INTEGER UNIQUE REFERENCES assessment_attempt(attempt_id),
                                     reversal_of_transaction_id    INTEGER UNIQUE REFERENCES mileage_transaction(mileage_transaction_id),
                                     transaction_type              VARCHAR(20) NOT NULL,
                                     points                        NUMERIC(10, 2) NOT NULL,
                                     transaction_status            VARCHAR(20) NOT NULL DEFAULT 'POSTED',
                                     requested_by                  INTEGER,
                                     processed_by                  INTEGER,
                                     transaction_reason            TEXT,
                                     posted_at                     TIMESTAMPTZ,
                                     created_at                    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     CONSTRAINT uq_mileage_transaction_source_assessment_attempt UNIQUE (source_assessment_attempt_id),
                                     CONSTRAINT fk_mileage_transaction_source_assessment_attempt FOREIGN KEY (source_assessment_attempt_id) REFERENCES assessment_attempt(attempt_id)
);


-- ============================================================================
-- 7. 주요 조회 인덱스 구성 (Performance Indexes)
-- ============================================================================

CREATE INDEX idx_counseling_schedule_type ON counseling_schedule(counseling_type_id);
CREATE INDEX idx_counseling_schedule_counselor ON counseling_schedule(counselor_id, starts_at);
CREATE INDEX idx_counseling_schedule_status ON counseling_schedule(schedule_status, starts_at);
CREATE INDEX idx_counseling_reservation_type ON counseling_reservation(counseling_type_id);
CREATE INDEX idx_counseling_reservation_schedule ON counseling_reservation(counseling_schedule_id);
CREATE INDEX idx_counseling_reservation_student ON counseling_reservation(student_id, created_at DESC);
CREATE INDEX idx_counseling_reservation_consent ON counseling_reservation(user_consent_id);
CREATE INDEX idx_counseling_reservation_processor ON counseling_reservation(processed_by);
CREATE INDEX idx_counseling_reservation_status ON counseling_reservation(reservation_status, created_at);
CREATE INDEX idx_counseling_assignment_counselor ON counseling_assignment(counselor_id, assigned_at);
CREATE INDEX idx_counseling_assignment_assigner ON counseling_assignment(assigned_by);
CREATE UNIQUE INDEX uq_counseling_assignment_active ON counseling_assignment(counseling_reservation_id) WHERE ended_at IS NULL;
CREATE INDEX idx_counseling_private_confirmer ON counseling_private_record(confirmed_by);
CREATE INDEX idx_psych_test_student ON psychological_test_result(student_id, tested_at DESC);
CREATE INDEX idx_psych_test_reservation ON psychological_test_result(counseling_reservation_id);
CREATE INDEX idx_counseling_proposal_student ON counseling_proposal(student_id, response_status);
CREATE INDEX idx_counseling_proposal_proposer ON counseling_proposal(proposed_by);
CREATE INDEX idx_counseling_proposal_reservation ON counseling_proposal(created_reservation_id);